spring:
  application:
    name: safely

  # 파일 업로드 용량 등 환경 무관 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JPA 기본 설정 (DB 종류와 무관한 부분)
  jpa:
    open-in-view: false # 성능 최적화를 위해 false 권장
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
      region:
        static: ap-northeast-2

# 기본적으로 dev 프로필을 활성화 (로컬에서 실행 시 자동 적용)
spring.profiles.active: dev