server:
  address: 0.0.0.0
  port: ${PORT:5000}

spring:
  config:
    activate:
      on-profile: prod
    # [핵심] AWS 파라미터 스토어의 값들을 내 설정처럼 불러옴
    import: "aws-parameterstore:/config/safely/"

  application:
    name: safely

  datasource:
    # url 삭제됨 (파라미터 스토어에서 자동 주입)
    driver-class-name: com.mysql.cj.jdbc.Driver
    # username 삭제됨 (파라미터 스토어에서 자동 주입)
    # password 삭제됨 (파라미터 스토어에서 자동 주입)

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      # Host, Port는 docker-compose.yml에서 받음
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      # password 삭제됨(redis 서버는 도커 컨테이너로 사이드카 방식을 사용하므로 REDIS PORT로의 외부 접속만 차단하면 되어서 비번 삭제함)

# jwt: 삭제됨 (파라미터 스토어에서 자동 주입)

logging:
  level:
    org.springframework: INFO # 운영에서는 INFO 이상으로 하는 게 좋음
    com.safely: INFO